# Generated by Django 4.2.5 on 2023-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('is_verified', models.BooleanField()),
            ],
        ),
    ]
